inner_steps: 500
checkpoint_freq: 200_000
eval_freq: 200_000
continue_training: false
max_train_hours: 24
model_selection_weight: 1.0
model_inference_loss_weight: 1.0
weight_by_complexity: True
track_ema: true
ema_decay: 0.999

defaults:
  - optimizer: radam
  - dataloader: datastream_large_batch
