name: StreamDataLoader
train_params:
  batch_size: 4096
  seed: 0
  num_batches: null
  simulation_device: cpu
  data_device: gpu
  device_index: 0
  jit_simulator: true
  return_numpy: true
  dataloader_kwargs:
    shuffle: false
    drop_last: false
    loop: true
    num_prefetch_host: 8
    num_prefetch_device: 4
    num_async_workers: 2
val_params:
  batch_size: 128
  seed: 123
  num_batches: null
  simulation_device: cpu
  data_device: gpu
  device_index: 0
  jit_simulator: true
  return_numpy: true
  dataloader_kwargs:
    shuffle: false
    drop_last: false
    loop: true
    num_prefetch_host: 4
    num_prefetch_device: 2
    num_async_workers: 1
