# Loading data
data_root: ${hydra:runtime.cwd}/data
data_folder: null
path: null
brain_mask: "nodif_brain_mask.nii.gz"
mri_data: "data.nii.gz"
bvals_data: "bvals"
bvecs_data: "bvecs"
round_bvals: true
clip_outliers: true
slice:
  x: null
  y: null
  z: null

# Loading model
results_root: ${hydra:runtime.cwd}/results
results_folder: null
path_checkpoint: null
model_name: "dmri"
params_name: "params_ema"

# Sampling configs
seed: 1
sample_mask: true
sample_theta: true
select_models: true
default_mask: null


defaults:
  - _self_
  - mask_sample: default
  - theta_sample: default
  - model_selection: none
  - export: ball3stick
  - export_model_selection: ball3stick
