schema_version: 2

run:
  name: dmri
  seed: 0

tracking:
  enabled: false
  wandb:
    project: dmri
    entity: null

simulator:
  posterior_score: false
  mask_prior: {}

hydra:
  run:
    dir: results/${run.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: results/${run.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

defaults:
  - _self_
  - simulator: ball3stick_shared
  - simulator/acquisition: multi
  - model: dmri
  - training: default
  - infrastructure/launcher: slurm
  - infrastructure/partition: none
