# F1-based accuracy metrics for model-selection predictions
key: model_selection_classification
type: model_selection_classification
output_filename: metric_model_selection_f1.nii.gz
batch_size: 20000
sample_reduction: none
sample_axis: 1
requires_theta_samples: false
write_summary: true
summary_filename: model_selection_classification_summary.json
options:
  threshold: 0.5
  classification_output_filename: model_selection_classification.json
aggregations:
  - type: mean
    name: mean_f1
  - type: median
    name: median_f1
