key: sbc_model_mask
type: sbc_model_mask
output_filename: metric_sbc_model_mask.nii.gz
batch_size: 20000
sample_reduction: none
sample_axis: 1
requires_theta_samples: false
write_summary: true
summary_filename: sbc_model_mask_summary.json
aggregations:
  - type: mean
    name: mean
  - type: median
    name: median
  - type: percentile
    q: [5, 95]
    name: p{q}
