name: SimulationDataset

dataset:
  simulation_batch_size: 2048
  buffer_size: 524288
  jit_simulator: true
  return_numpy: false
  simulation_device:
    kind: cpu
    index: 0

train_loader:
  batch_size: 2048
  shuffle: true
  drop_last: true
  loop: true
  num_prefetch_host: 8
  num_prefetch_device: 8
  num_async_workers: 1

val_dataset:
  buffer_size: 2048
  simulation_batch_size: 64

val_loader:
  batch_size: 128
  shuffle: false
  drop_last: false
  loop: true
  num_prefetch_host: 8
  num_prefetch_device: 2
