# Mean absolute reconstruction error across posterior samples
key: reconstruction_mse
type: reconstruction_mse
output_filename: error_reconstruction.nii.gz
batch_size: 10_000
sample_reduction: mean
sample_axis: 1
requires_theta_samples: true
write_summary: true
summary_filename: reconstruction_mse_summary.json
aggregations:
  - type: mean
    name: mean
  - type: std
    name: std
  - type: percentile
    q: [5, 95]
    name: p{q}
